INSERT INTO VEHICULOS (ID, COLOR, FECHA_CREACION_REGISTRO, LINEA, MARCA, MODELO_AUTO, PLACA) VALUES (1, 'ROJO', '2019-09-04', 'SEDAN',' MAZDA', '2010', 'MAH617');
INSERT INTO VEHICULOS (ID, COLOR, FECHA_CREACION_REGISTRO, LINEA, MARCA, MODELO_AUTO, PLACA) VALUES (2, 'ROJO', '2019-09-04', 'SEDAN',' MAZDA', '2010', 'MAH617');
INSERT INTO VEHICULOS (ID, COLOR, FECHA_CREACION_REGISTRO, LINEA, MARCA, MODELO_AUTO, PLACA) VALUES (3, 'ROJO', '2019-09-04', 'SEDAN',' MAZDA', '2010', 'MAH617');
INSERT INTO VEHICULOS (ID, COLOR, FECHA_CREACION_REGISTRO, LINEA, MARCA, MODELO_AUTO, PLACA) VALUES (4, 'ROJO', '2019-09-04', 'SEDAN',' MAZDA', '2010', 'MAH617');
INSERT INTO VEHICULOS (ID, COLOR, FECHA_CREACION_REGISTRO, LINEA, MARCA, MODELO_AUTO, PLACA) VALUES (5, 'ROJO', '2019-09-04', 'SEDAN',' MAZDA', '2010', 'MAH617');
INSERT INTO VEHICULOS (ID, COLOR, FECHA_CREACION_REGISTRO, LINEA, MARCA, MODELO_AUTO, PLACA) VALUES (6, 'ROJO', '2019-09-04', 'SEDAN',' MAZDA', '2010', 'MAH617');
INSERT INTO VEHICULOS (ID, COLOR, FECHA_CREACION_REGISTRO, LINEA, MARCA, MODELO_AUTO, PLACA) VALUES (7, 'ROJO', '2019-09-04', 'SEDAN',' MAZDA', '2010', 'MAH617');
INSERT INTO VEHICULOS (ID, COLOR, FECHA_CREACION_REGISTRO, LINEA, MARCA, MODELO_AUTO, PLACA) VALUES (8, 'ROJO', '2019-09-04', 'SEDAN',' MAZDA', '2010', 'MAH617');
